[package]
name = "sn-hardware"
version = "0.1.0"
edition = "2021"
authors = ["rage - rage997.github.io"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
